@Agent.Api_HostAddress = http://localhost:5050

POST {{Agent.Api_HostAddress}}/test-emmbedded/
Content-Type: application/json
{
    "message": "I want to clearify and create roadmap for 2026",
    "conversationId": "111"
}
###

POST {{Agent.Api_HostAddress}}/api/skills/vector-search
Content-Type: application/json
{
    "message": "fintech?",
    "conversationId": "111"
}
###
